steps:
  # 1. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/mssql-cdc-sync:latest', '.']

  # 2. Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/mssql-cdc-sync:latest']

  # 3. Deploy/Update Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'cdc-sync-job'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/mssql-cdc-sync:latest'
      - '--region'
      - 'asia-southeast1'
      # --- CẤU HÌNH TÀI NGUYÊN ---
      - '--memory'
      - '4Gi'             # Tăng lên 4GB RAM để tránh lỗi OOM
      - '--cpu'
      - '2'               # 2 vCPU cho khỏe
      - '--task-timeout'
      - '7200s'           # 7200 giây = 2 Tiếng (Để tải 7GB không bị cắt)
      - '--service-account'
      - 'airbyte-connect@pacc-raw-data.iam.gserviceaccount.com' # <--- QUAN TRỌNG: SA CỦA BẠN Ở ĐÂY
      - '--set-env-vars'
      - 'BQ_PROJECT=$PROJECT_ID'
      - '--set-env-vars'
      - 'STATE_BUCKET=my-cdc-state-bucket'
      - 'FILTER_CONNECTION_ID=conn_acc'
      # Lưu ý: Passwords nên dùng Secret Manager, đây là ví dụ env vars thường
      - '--set-env-vars'
      - 'MSSQL_SERVER=203.171.28.250'
      - '--set-env-vars'
      - 'MSSQL_DB=IACC_BGPACC2024'
      - '--set-env-vars'
      - 'MSSQL_USER=namba'
      - '--set-env-vars'
      - 'MSSQL_PASS=R2YUUCR7xN4aF5' 

  # 4. Sale db job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'cdc-sync-job-sales'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/mssql-cdc-sync:latest'
      - '--region'
      - 'asia-southeast1'
      # --- CẤU HÌNH TÀI NGUYÊN ---
      - '--memory'
      - '2Gi'             # Tăng lên 4GB RAM để tránh lỗi OOM
      - '--cpu'
      - '2'               # 2 vCPU cho khỏe
      - '--task-timeout'
      - '7200s'           # 7200 giây = 2 Tiếng (Để tải 7GB không bị cắt)
      - '--service-account'
      - 'airbyte-connect@pacc-raw-data.iam.gserviceaccount.com' # <--- QUAN TRỌNG: SA CỦA BẠN Ở ĐÂY
      - '--set-env-vars'
      - 'BQ_PROJECT=$PROJECT_ID'
      - '--set-env-vars'
      - 'STATE_BUCKET=my-cdc-state-bucket-sales'
      - 'FILTER_CONNECTION_ID=conn_sales' 
      # Lưu ý: Passwords nên dùng Secret Manager, đây là ví dụ env vars thường
      - '--set-env-vars'
      - 'MSSQL_SERVER=203.171.29.166'
      - '--set-env-vars'
      - 'MSSQL_DB=IPOSSBGN'
      - '--set-env-vars'
      - 'MSSQL_USER=namba'
      - '--set-env-vars'
      - 'MSSQL_PASS=T3uB6duJJaRcKE!' 

options:
  logging: CLOUD_LOGGING_ONLY